version: 2
formats: all

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

python:
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
    - method: pip
      path: .
  system_packages: true
